export const events = [
  {
    category: "Social",
    title: "Electrosteel Proudly Partners with Daamini",
    date: "October 30",
    time: "12:00 am",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/card/e1.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Conference",
    title: "Electrosteel Etiam in Tristique Nunc Diam",
    date: "November 7",
    time: "09:00 am",
    location: "Akhilesh Bhavan, Ranchi",
    image: "/images/events/card/e2.jpg",
    link: "/newsroom/events/events1",
  },
  {
    category: "International",
    title: "Electrosteel Sed Nec Nulla Vel Nisi Rutrum",
    date: "November 13",
    time: "12:00 am",
    location: "Derbyshire, UK",
    image: "/images/events/card/e3.jpg",
    link: "/newsroom/events/events1",
  },
  {
    category: "Environment",
    title: "Electrosteel Integer Turpis Enim, Rutrum Vel",
    date: "November 18",
    time: "12:00 am",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/card/e4.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Sports",
    title: "Electrosteel Teger Urpis Enim Rutrum Vel",
    date: "December 1",
    time: "12:00 am",
    location: "Delhi, India",
    image: "/images/events/card/e5.jpg",
    link: "/newsroom/events/events1",
  },
  {
    category: "International",
    title: "Electrosteel Elementum at Diam Fusce",
    date: "December 15",
    time: "09:00 am",
    location: "New Market, Ranchi",
    image: "/images/events/card/e6.jpg",
    link: "/newsroom/events/events1",
  }
];

export const latestEvents = [
  {
    category: "Social",
    title: "Electrosteel Proudly Partners with Daamini",
    date: "September 16, 2024",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e1.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "Republic Day Celebration 2024",
    date: "January 26, 2024",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e2.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "Ubharte Sitare - a CSR initiative at SW plant",
    date: "May 11, 2023",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e3.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "International Women's Day, 2023",
    date: "March 8, 2023",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e4.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "Ms Priya Manjari Todi becomes Chairperson CII Tirupati Zone",
    date: "February 27, 2023",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e5.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "Celebration of International Mother Language Day",
    date: "February 21, 2023",
    // time: "09:00 am",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e6.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "Donation towards Annadaan - Food for Life",
    date: "January 10, 2023",
    location: "Netaji Indoor, Kolkata",
   image: "/images/events/latestEvents/e7.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "X-mas and New year's Video",
    date: "December 25, 2022",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e8.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "Children's Day celebrations",
    date: "November 14, 2022",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e9.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "Well Being Through Expressive Arts",
    date: "November 9, 2022",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e10.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "Business Excellence Awards 2022",
    date: "September 12, 2022",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e11.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "Independence Day 2022",
    date: "August 15, 2022",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e12.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "World Environment Day, 2022",
    date: "June 5, 2022",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e13.png",
    link: "/newsroom/events/events1",
  },
  {
    category: "Social",
    title: "Mother's Day, 2022",
    date: "May 8, 2022",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/latestEvents/e14.png",
    link: "/newsroom/events/events1",
  },
];

