export const events = [
  {
    category: "Social",
    title: "Electrosteel Proudly Partners with Daamini",
    date: "October 30",
    time: "12:00 am",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/card/e1.png",
    link: "#",
  },
  {
    category: "Conference",
    title: "Electrosteel Etiam in Tristique Nunc Diam",
    date: "November 7",
    time: "09:00 am",
    location: "Akhilesh Bhavan, Ranchi",
    image: "/images/events/card/e2.jpg",
    link: "#",
  },
  {
    category: "International",
    title: "Electrosteel Sed Nec Nulla Vel Nisi Rutrum",
    date: "November 13",
    time: "12:00 am",
    location: "Derbyshire, UK",
    image: "/images/events/card/e3.jpg",
    link: "#",
  },
  {
    category: "Environment",
    title: "Electrosteel Integer Turpis Enim, Rutrum Vel",
    date: "November 18",
    time: "12:00 am",
    location: "Netaji Indoor, Kolkata",
    image: "/images/events/card/e4.png",
    link: "#",
  },
  {
    category: "Sports",
    title: "Electrosteel Teger Urpis Enim Rutrum Vel",
    date: "December 1",
    time: "12:00 am",
    location: "Delhi, India",
    image: "/images/events/card/e5.jpg",
    link: "#",
  },
  {
    category: "International",
    title: "Electrosteel Elementum at Diam Fusce",
    date: "December 15",
    time: "09:00 am",
    location: "New Market, Ranchi",
    image: "/images/events/card/e6.jpg",
    link: "#",
  }
];
